### ISSUE TITLE
Tablet use

### ISSUE THREAD

**Issue by theryex** [Sanster/IOPaint#210]
I have a Wacom Cintique tablet, and whenever I try to use the pen to draw the mask, it only tries to move the image as if I was using a touch screen. It doesn't appear to work for drawing masks in either the windows GUI or running it on an instance of Chrome/Firefox.

**Comment by negimeister** [comment]
The same also happens with mobile devices. I host lama on my server and would like to use it from my Android tablet but both the touchscreen and the pen only move the canvas.
