### ISSUE TITLE
How to use mask for automating watermark removal for all images inside folder

### ISSUE THREAD

**Issue by yashb042** [Sanster/IOPaint#392]
I see the mask feature in which I can add a mask and the photo can be changed. 2 questions :

1. How to play the mask for all the photos inside the directory, currently I have to manually select a photo and then do it.
2. How to automate the process, maybe using CLI, instead of me going on the UI.

**Comment by StanislavZayarsky** [comment]
Any thoughts here?

**Comment by Sanster** [comment]
You can use the iopaint run command in the command line (lama-cleaner has been renamed to iopaint): https://www.iopaint.com/batch_process
