### ISSUE TITLE
[Feature Request] - Incorporate "AnyText" to allow for fixing of text on images

### ISSUE THREAD

**Issue by CCpt5** [Sanster/IOPaint#418]
Hello! 

I noticed there is a new repo called "AnyText" that seems to allow for the correction of written text. Pretty sure the code is now available as well. Repo:

https://github.com/tyxsspa/AnyText

Would it be possible to incorporate this into a future version of lama-cleaner to allow for text correction? I've been hoping for a method to fix poorly generated txt (by Stable Diffusion etc) for a long time now. Perhaps this could finally provide a solution.

Would love your feedback on the capability of their code and whether or not you think it could appear in a future version of lama-cleaner.

Thanks and happy new year!!

**Comment by Sanster** [comment]
The result of the AnyText model looks great, and I am currently working on refactoring the front-end and back-end code of lama-cleaner in [this branch](https://github.com/Sanster/lama-cleaner/tree/0829). Once the refactoring is complete, I will add this model.
