### ISSUE TITLE
[Bug] Local install fails with `ValueError: path './' cannot end with '/'`

### ISSUE THREAD

**Issue by TFWol** [Sanster/IOPaint#427]
On Windows, cloning the project and running `pip install .` where setup.py is located will fail with 

```
File "C:\Users\User\AppData\Local\Temp\pip-build-env-ywu3d7ww\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 141, in convert_path
          raise ValueError("path '%s' cannot end with '/'" % pathname)
      ValueError: path './' cannot end with '/'
```
To make it work, I had to change this:
https://github.com/Sanster/lama-cleaner/blob/fd74b8556f1f7a22dc6705c85336830c8987c84e/setup.py#L31

To This:
```python
packages=setuptools.find_packages(),
```
Removing the `./`

**Comment by Sanster** [comment]
fixed in https://github.com/Sanster/IOPaint/commit/71351f68a704704f625c8a78e4d70e6ece40f87d
