### ISSUE TITLE
[BUG]Brush disappear after press mouse middle key to move image

### ISSUE THREAD

**Issue by acyclic0725** [Sanster/IOPaint#440]
**Model**
Which model are you using?
lama/sd1.5
**Describe the bug**
When use io paint, the brush disappears after press mouse middle key to move image.
lama_cleaner does not have the problem.

**System Info**
Software version used
- lama-cleaner: [fcd8254](https://github.com/Sanster/IOPaint/commit/fcd825420501bb4828ebfd6761507acabba1bda0)
- pytorch: 2.0.1
- CUDA: 11.8

**Comment by Sanster** [comment]
fixed in `iopaint==1.0.1`
