### ISSUE TITLE
[Feature Request] decrease the brush size limit

### ISSUE THREAD

**Issue by klnaD** [Sanster/IOPaint#455]
can u decrease the brush size limit.
it is really hard to highlight small areas because the smallest brush size is little bit bigger

**Comment by LoganTann** [comment]
Use the slider to change the brush size : 

![image](https://github.com/Sanster/IOPaint/assets/28659185/e6135f04-b64b-48e3-8c0f-fe520adce5fc)

**Comment by LoganTann** [comment]
Don't forget to close this issue if I answered your question.

**Comment by Sanster** [comment]
Hi, in the new version (1.2.0) the minimum size of the brush has been adjusted from 10 to 3.
