### ISSUE TITLE
[BUG] White Page and nothing with error(in chrome dev tool console) Page blocked because of a disallowed MIME type "text/plain"

### ISSUE THREAD

**Issue by AndrewDrimer** [Sanster/IOPaint#460]
![2024-02-23_040903](https://github.com/Sanster/IOPaint/assets/31075368/d144a285-18e9-43a2-b5d1-50544b8e64b9)
Server loading but only White web. Nothing else. What wrong?

**Comment by Sanster** [comment]
It may be that there are errors in the front-end webpage. Could you please open the developer tools in Chrome to see if there are any errors? Thank you.

Other people have also encountered this problem, and it seems that refreshing the page can solve the issue.

**Comment by AndrewDrimer** [comment]
![2024-02-23_041934](https://github.com/Sanster/IOPaint/assets/31075368/45b9eddb-a6f2-4a30-800c-6f3dd97b83d1)

**Comment by AndrewDrimer** [comment]
![2024-02-23_043643](https://github.com/Sanster/IOPaint/assets/31075368/fd365241-65c8-40f6-b4ef-70b9a161df64)
I Change This. Reload Working. 
![2024-02-23_043850](https://github.com/Sanster/IOPaint/assets/31075368/014eed6e-d3e0-4d7b-93e3-35ab03d04adf)

**Comment by Sanster** [comment]
wow, thank you for your report, I will investigate why this is happening.

**Comment by ffoofooffof** [comment]
I had the same issue. Thank you for the solution.

**Comment by ggardlo** [comment]
I had the same issue, try to refresh page. It helped to me.

**Comment by Xiuzhenpeng** [comment]
I had the same issue.I try this, and donnot work. but I change this, it is working. Thank you.
![屏幕截图(65)](https://github.com/Sanster/IOPaint/assets/133330262/a9d9aacf-e106-436c-ac73-eb30d1e834a2)


> ![2024-02-23_043643](https://private-user-images.githubusercontent.com/31075368/307209461-fd365241-65c8-40f6-b4ef-70b9a161df64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDk3NzMsIm5iZiI6MTcwODg0OTQ3MywicGF0aCI6Ii8zMTA3NTM2OC8zMDcyMDk0NjEtZmQzNjUyNDEtNjVjOC00MGY2LWI0ZWYtNzBiOWExNjFkZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA4MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZjBmMzgwOWI2NDU4NGQ5ZjNjMWM1MWUyN2IzYTI1ZWJhZDYzMTNlYTY0OTJkMDJkNGFlMGNkZjViMjU2ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rbENfXFdohwb7MGPXWXn_jm7kl0kMWZ4UoH6rRh2Qs0) I Change This. Reload Working. 我改变这个。重新加载工作。 ![2024-02-23_043850](https://private-user-images.githubusercontent.com/31075368/307209587-014eed6e-d3e0-4d7b-93e3-35ab03d04adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDk3NzMsIm5iZiI6MTcwODg0OTQ3MywicGF0aCI6Ii8zMTA3NTM2OC8zMDcyMDk1ODctMDE0ZWVkNmUtZDNlMC00ZDdiLTkzZTMtMzVhYjAzZDA0YWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA4MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxY2UzMDk5OGEwZWU4YjdiOWRmNWJhMmJlZjFiNjMwMTFhNTYwNTM4YTQ3ZjAwZjA2YTcyNGFhODVhYTg4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOW2qUpkZw950eaJixVEB6Vi2vzko_lAMjtnNJOkHOU)

**Comment by nikolaiusa** [comment]
+1 white screen - console log:
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by nikolaiusa** [comment]
works at Microsoft edge
doesn't work in chrome, cent browser... (white screen)

**Comment by Pudzianos** [comment]
Also got this error, changing registry does not work for me and It happens on all my browsers (chrome,edge,opera,firefox)
![msedge_yYkYm1ZqWw](https://github.com/Sanster/IOPaint/assets/127506462/4fb96eca-56ae-4d9d-bea3-48532f66bf1f)
![firefox_zGq7zfUKb5](https://github.com/Sanster/IOPaint/assets/127506462/0c838ed3-29a8-4f59-bf39-a2a859ff18bf)

**Comment by Sanster** [comment]
> Also got this error, changing registry does not work for me and It happens on all my browsers (chrome,edge,opera,firefox) ![msedge_yYkYm1ZqWw](https://private-user-images.githubusercontent.com/127506462/311548207-4fb96eca-56ae-4d9d-bea3-48532f66bf1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTEwNjQsIm5iZiI6MTcxMDE1MDc2NCwicGF0aCI6Ii8xMjc1MDY0NjIvMzExNTQ4MjA3LTRmYjk2ZWNhLTU2YWUtNGQ5ZC1iZWEzLTQ4NTMyZjY2YmYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwOTUyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjMxNjJkZDRiN2ZhNWU0MTllM2RkNTM1YTQ3NWE4YjlkMDk5OTcxMmJiZWI3OWUyNTBjODFhZDkxMWYxNWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xoAO8q8zeGmvVej7Wi9MDbaH9wzHA1QwRDTzZw_N2nI) ![firefox_zGq7zfUKb5](https://private-user-images.githubusercontent.com/127506462/311548384-0c838ed3-29a8-4f59-bf39-a2a859ff18bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTEwNjQsIm5iZiI6MTcxMDE1MDc2NCwicGF0aCI6Ii8xMjc1MDY0NjIvMzExNTQ4Mzg0LTBjODM4ZWQzLTI5YTgtNGY1OS1iZjM5LWEyYTg1OWZmMThiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwOTUyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTgxNTYzODg3OWU5N2U0MjIyMTU0YTJmM2U3YjE0MzA1NDk0OTcyOWEyYWZiNTAwOWI3OWFmM2U3OTNiOTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNWfzddAFy485FUPA8elHx7QJzjq0wSu7TZWZPUT6WE)

I found some issues in other projects that encountered this problem, they are basically related to Windows registry settings. Perhaps you can refer to how others have solved problems in these issues：
- https://github.com/invoke-ai/InvokeAI/issues/3702
- https://github.com/voxel51/fiftyone/issues/2010
- https://github.com/golang/go/issues/32350

**Comment by Pudzianos** [comment]
In my case pull request still didn't work
It helped after I changed this in both places AND then restarted my PC
https://github.com/voxel51/fiftyone/issues/2522#issuecomment-1457862951

Thank you :)
