### ISSUE TITLE
[BUG]version issue of Pillow while installing iopaint

### ISSUE THREAD

**Issue by LokeshBadisa** [Sanster/IOPaint#461]
**Describe the bug**
While installing iopaint with `pip install iopaint`, I get a `Could not build wheels for Pillow, which is required to install pyproject.toml-based projects` which probably could be an incompatibility with `Pillow` and other packages. I tried installing `iopaint==1.0.0` but still same error.

**System Info**
Software version used
- iopaint: 1.2.0
- python: 3.12.1
- conda: 23.3.1
- pip(within conda): 23.3.1

**Comment by Sanster** [comment]
Maybe it's because your Python version is too new, can you try 3.10?

**Comment by LokeshBadisa** [comment]
Python version 3.10 is working.
