### ISSUE TITLE
[Feature Request] Multiple zones to clean at once.

### ISSUE THREAD

**Issue by LoganTann** [Sanster/IOPaint#462]
**Is your feature request related to a problem? Please describe.**

I use this wonderful tool to clean manga pages. I have multiple small zones to erase, and each of them take up to one minute.

**Describe the solution you'd like**

Is it possible to allow the user enabling an option to select multiple zones, and erase them in one batch ?

**Additional context**
none

**Comment by wr4thful** [comment]
perhaps this is the feature ur referring to. its in the settings
![1](https://github.com/Sanster/IOPaint/assets/143463195/f3d1befa-8222-488b-9107-682769a268cb)

**Comment by LoganTann** [comment]
This is exactly what I was looking for, thanks !
