### ISSUE TITLE
inpainting workflow and how to update the program via cli

### ISSUE THREAD

**Issue by wr4thful** [Sanster/IOPaint#463]
hi, ive used the program couple times in the past and i installed it via the command
`pip3 install iopaint`
however i dont understand how to update it to the most recent version. 

regarding inpainting workflow, i am trying to remove some object from this image
![15-1](https://github.com/Sanster/IOPaint/assets/143463195/ab1f0e0d-23eb-4200-82ca-40e5bcc4bb5a)

however any attempt results unusable output, regardless of steps that i use. they seem to produce unwanted results.
i am not sure if i need to fill the prompt bar or leave it blank. i just wanted to inpaint the masked area to remove the mother and son. i tried both and the results were the same. i am also not sure if i need to leave the default negative prompt or clear them blank because both also did not give different results. am i doing something wrong? what would be the best approach for my current situation

![brave_2024-02-25_08 50 56](https://github.com/Sanster/IOPaint/assets/143463195/d6587037-01c8-46e9-a90d-0bf6a9fd4803)

looking forward and will appreciate for any responses and help, thanks :)

**Comment by Sanster** [comment]
You can use `pip install -U iopaint` to update 

I tried your image for a few minutes and this is the result I obtained (the edges of the inpainting region and man's hand are not good enough yet).

![307561745-ab1f0e0d-23eb-4200-82ca-40e5bcc4bb5a_cleanup](https://github.com/Sanster/IOPaint/assets/3998421/0a5e8ea0-d59d-473a-a8db-b143258d9f21)

The configuration used is as follows: 

# step1-remove woman
<img width="1453" alt="remove_woman" src="https://github.com/Sanster/IOPaint/assets/3998421/5b8218c6-2b67-484f-898b-1e14c7f3855d">

# step2-remove child

<img width="1655" alt="remove_child" src="https://github.com/Sanster/IOPaint/assets/3998421/4d36bcc4-83b5-445c-b26b-2e3d5f368c0c">

**Comment by wr4thful** [comment]
thanks for the reply. thats a really good decent result, also helps me understand the approach better. im gonna try the same config myself. i think for now i can use some image editing to dissolve the edge artifacts but thats a really decent results to work with. again thanks :)

**Comment by Sanster** [comment]
I discovered a way to achieve better results. The model and configuration used can be seen from the video.

https://github.com/Sanster/IOPaint/assets/3998421/f13d27ef-fe2a-4dad-823b-e4de801b0a16

Result image

![307561745-ab1f0e0d-23eb-4200-82ca-40e5bcc4bb5a_cleanup (1)](https://github.com/Sanster/IOPaint/assets/3998421/c1df92a2-5e3d-4d8e-99f9-206b1bf970b4)

**Comment by wr4thful** [comment]
> I discovered a way to achieve better results. The model and configuration used can be seen from the video.
> 
>  lcm_remove.mp4 
> Result image
> 
> ![307561745-ab1f0e0d-23eb-4200-82ca-40e5bcc4bb5a_cleanup (1)](https://private-user-images.githubusercontent.com/3998421/308211531-c1df92a2-5e3d-4d8e-99f9-206b1bf970b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDU4NTcsIm5iZiI6MTcwOTUwNTU1NywicGF0aCI6Ii8zOTk4NDIxLzMwODIxMTUzMS1jMWRmOTJhMi01ZTNkLTRkOGUtOTlmOS0yMDZiMWJmOTcwYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMjIzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2NDhmZjdkMTE5MDYzMzk4OWU1NmVjYjNjZDYyMjJjMDEwODFlY2NkNDE2NjM4MjM5MWZiYWU3ZmU5MzliMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ft-pvDZa4Lp06jiUqJMlNDgVoaQ504ZLuRf8mIb2O9M)

that result is actually insane. i had to mess for some minutes in photoshop to smooth and refine things out before but i guess that is not necessary anymore knowing this. truly appreciate the help, havent checked github for a while so sorry for the late responses. but anyways thanks 👍
