### ISSUE TITLE
有考虑增加自动识别水印位置去除吗？

### ISSUE THREAD

**Issue by qq14909** [Sanster/IOPaint#477]
这个可以识别水印位置，但是不能去除，https://github.com/Kamino666/watermark-tracer

或者太复杂的话能否添加蒙版去除水印

**Comment by qq14909** [comment]
抱歉，我没有注意到已经有添加蒙版去除水印功能

**Comment by dontknowhy** [comment]
请**不要**在英文社区发中文issue.
又不是什么全世界讲中国话的地方，尤其是GitHub网页本身都没中文支持，大部分人也都是使用英文。
