### ISSUE TITLE
请问有纯命令行调用的模式吗？

### ISSUE THREAD

**Issue by joseph16388** [Sanster/IOPaint#489]
作者 @Sanster 你好，有没有不用启动服务端，纯命令行可以运行的模式呢？谢谢！
就是比如：IOPaint.exe -i input.jpg -m mask -o output.jpg这种形式CLI的支持呢？

**Comment by Sanster** [comment]
有的，`pip install iopaint` 后可以通过 `iopaint run` 在命令行支持批量处理，可以通过 `iopaint run --help` 查看参数

**Comment by NKdryer** [comment]
@Sanster 你好，请问怎么在命令行执行outpaint操作？需要下载哪几个模型？

**Comment by joseph16388** [comment]
> 有的，`pip install iopaint` 后可以通过 `iopaint run` 在命令行支持批量处理，可以通过 `iopaint run --help` 查看参数

好的，感谢！

**Comment by yumianhuli1** [comment]
> 有的，`pip install iopaint` 后可以通过 `iopaint run` 在命令行支持批量处理，可以通过 `iopaint run --help` 查看参数

不过试了下，原来几十kb的图片变几Mb，怎么配置减小尺寸哈？

**Comment by joseph16388** [comment]
> 有的，`pip install iopaint` 后可以通过 `iopaint run` 在命令行支持批量处理，可以通过 `iopaint run --help` 查看参数

不过试了下，经过处理后原来几十kb的图片变几Mb，怎么配置减小尺寸哈？
