### ISSUE TITLE
Error When Using 1-Click Installer

### ISSUE THREAD

**Issue by EvenZH1102** [Sanster/IOPaint#495]
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\IOPaint\installer\lib\site-packages\iopaint\cli.py:221 in start_web_config                    │
│                                                                                                  │
│   218 │   config_file: Path = Option("config.json"),                                             │
│   219 ):                                                                                         │
│   220 │   dump_environment_info()                                                                │
│ > 221 │   from iopaint.web_config import main                                                    │
│   222 │                                                                                          │
│   223 │   main(config_file)                                                                      │
│   224                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\iopaint\web_config.py:18 in <module>                      │
│                                                                                                  │
│    15 from datetime import datetime                                                              │
│    16 from json import JSONDecodeError                                                           │
│    17                                                                                            │
│ >  18 import gradio as gr                                                                        │
│    19 from iopaint.download import scan_models                                                   │
│    20 from loguru import logger                                                                  │
│    21                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\__init__.py:3 in <module>                          │
│                                                                                                  │
│     1 import json                                                                                │
│     2                                                                                            │
│ >   3 import gradio._simple_templates                                                            │
│     4 import gradio.image_utils                                                                  │
│     5 import gradio.processing_utils                                                             │
│     6 import gradio.templates                                                                    │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\_simple_templates\__init__.py:1 in <module>        │
│                                                                                                  │
│ > 1 from .simpledropdown import SimpleDropdown                                                   │
│   2 from .simpleimage import SimpleImage                                                         │
│   3 from .simpletextbox import SimpleTextbox                                                     │
│   4                                                                                              │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\_simple_templates\simpledropdown.py:6 in <module>  │
│                                                                                                  │
│     3 import warnings                                                                            │
│     4 from typing import Any, Callable                                                           │
│     5                                                                                            │
│ >   6 from gradio.components.base import FormComponent                                           │
│     7 from gradio.events import Events                                                           │
│     8                                                                                            │
│     9                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\components\__init__.py:40 in <module>              │
│                                                                                                  │
│    37 from gradio.components.logout_button import LogoutButton                                   │
│    38 from gradio.components.markdown import Markdown                                            │
│    39 from gradio.components.model3d import Model3D                                              │
│ >  40 from gradio.components.multimodal_textbox import MultimodalTextbox                         │
│    41 from gradio.components.number import Number                                                │
│    42 from gradio.components.paramviewer import ParamViewer                                      │
│    43 from gradio.components.plot import Plot                                                    │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\components\multimodal_textbox.py:34 in <module>    │
│                                                                                                  │
│    31                                                                                            │
│    32                                                                                            │
│    33 @document()                                                                                │
│ >  34 class MultimodalTextbox(FormComponent):                                                    │
│    35 │   """                                                                                    │
│    36 │   Creates a textarea for users to enter string input or display string output and also   │
│    37                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\component_meta.py:198 in __new__                   │
│                                                                                                  │
│   195 │   │   if "EVENTS" in attrs:                                                              │
│   196 │   │   │   attrs["EVENTS"] = new_events                                                   │
│   197 │   │   component_class = super().__new__(cls, name, bases, attrs)                         │
│ > 198 │   │   create_or_modify_pyi(component_class, name, events)                                │
│   199 │   │   return component_class                                                             │
│   200                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\site-packages\gradio\component_meta.py:92 in create_or_modify_pyi       │
│                                                                                                  │
│    89 ):                                                                                         │
│    90 │   source_file = Path(inspect.getfile(component_class))                                   │
│    91 │                                                                                          │
│ >  92 │   source_code = source_file.read_text()                                                  │
│    93 │                                                                                          │
│    94 │   current_impl, lineno = extract_class_source_code(source_code, class_name)              │
│    95                                                                                            │
│                                                                                                  │
│ C:\IOPaint\installer\lib\pathlib.py:1135 in read_text                                            │
│                                                                                                  │
│   1132 │   │   """                                                                               │
│   1133 │   │   encoding = io.text_encoding(encoding)                                             │
│   1134 │   │   with self.open(mode='r', encoding=encoding, errors=errors) as f:                  │
│ > 1135 │   │   │   return f.read()                                                               │
│   1136 │                                                                                         │
│   1137 │   def write_bytes(self, data):                                                          │
│   1138 │   │   """                                                                               │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

**Comment by Sanster** [comment]
Fixed in `iopaint==1.2.3`, mainly due to issues caused by the new version of gradio. Running `win_config.bat` again will automatically upgrade to the new version.
