### ISSUE TITLE
How to run more than one model

### ISSUE THREAD

**Issue by OmarAboRabea1** [Sanster/IOPaint#510]
how can I run more than one model from the same command:
for running the app I use this:

docker run -it -p 8080:8080 --entrypoint /bin/bash dockerID -c "pip install --no-cache-dir -r requirements.txt && apt-get update && apt-get install -y libglib2.0-0 && apt-get install -y libgl1 && python3 main.py start --host 0.0.0.0 --model fcf"

I want to also run the lama model. How can I do this? 
I tried this but it didn't work: "python3 main.py start --host 0.0.0.0 --model fcf --model lama"

**Comment by lovegnep** [comment]
also want to know

**Comment by Sanster** [comment]
Sorry, loading multiple models at the same time is not supported. If you are looking to compare the effects of different models, it is recommended to prepare the images and corresponding masks, and then use the `iopaint run` command to batch process different models.
