### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Reginald-L** [Sanster/IOPaint#516]
Hi, thanks very much for your work. when I run the code base Development rules, got a network error, may I get your help?
1. npm install --- under web_app
2. add a .env.local file --- VITE_BACKEND=http://127.0.0.1:9999
3. npm run dev ---- http://localhost:5173/
4. error message on console
![image](https://github.com/Sanster/IOPaint/assets/67569154/20b0c6d7-5ff3-4620-8da3-d3b6dac3c7f2)
![error1](https://github.com/Sanster/IOPaint/assets/67569154/86fd0ee0-540c-43d1-83a7-080134fbbf7d)

**Comment by Sanster** [comment]
Front-end development requires starting the corresponding backend service.

```bash
pip install -r requirements.txt
python3 main.py --model lama --port 9999
```

**Comment by Reginald-L** [comment]
> Front-end development requires starting the corresponding backend service.
> 
> ```shell
> pip install -r requirements.txt
> python3 main.py --model lama --port 9999
> ```
Thanks very much for your response, I tried these instructions, but the problem is still remain. It seems that the end program is not running.
I tried running 'python3 main.py --model lama --port 9999' both before and after npm run dev 
![image](https://github.com/Sanster/IOPaint/assets/67569154/cf4bb898-e314-4a7f-b812-05b3361a185e)

**Comment by Sanster** [comment]
Executing `python3 main.py --model lama --port 9999` and executing `iopaint start --model lama --port 9999` should be the same. It looks like your command line didn't print any information when executing `python3 main.py`, I'm not sure what the issue is.

If you do not need to modify the backend code, executing `iopaint start --model lama --port 9999` indeed works as well.

**Comment by Reginald-L** [comment]
> Executing `python3 main.py --model lama --port 9999` and executing `iopaint start --model lama --port 9999` should be the same. It looks like your command line didn't print any information when executing `python3 main.py`, I'm not sure what the issue is.
> 
> If you do not need to modify the backend code, executing `iopaint start --model lama --port 9999` indeed works as well.

cool, thanks very much for your help and perfect work
