### ISSUE TITLE
[Feature Request] Speed up the windows installer download speed

### ISSUE THREAD

**Issue by hgx127** [Sanster/IOPaint#521]
** The windows installer download speed is very slow.**
I have purchased the installation package, but the download speed from China is very slow and often fails due to network issues.
<img width="511" alt="image" src="https://github.com/Sanster/IOPaint/assets/3786694/a04015b0-bc29-4040-9743-3326f7c51432">
![image](https://github.com/Sanster/IOPaint/assets/3786694/d579119f-b562-4209-9ba1-092f2d993cbc)

**Describe the solution you'd like**
Please provide the download link of mega disk or Google cloud disk or onedrive to solve this problem.

**Comment by Styx233** [comment]
我上传百度网盘了

**Comment by Sanster** [comment]
@hgx127 hi 我已经给你发送了 google drive 的共享链接了，你收到了吗？
