### ISSUE TITLE
[BUG] Windows 1-click Installer "ImportError: cannot import name 'deprecated' from 'typing_extensions' "

### ISSUE THREAD

**Issue by choomaque** [Sanster/IOPaint#526]
**Model**
1.24 I guess

**Describe the bug**
1. Click 'win_start.bat'
2. cmd.exe opens with "ImportError: cannot import name 'deprecated' from 'typing_extensions' " error
3. cmd.exe closes when pressing any key

**Screenshots**
  

**System Info**
Software version used
windows 1-click installer, I don't know how to check version in 1-click installer

**Comment by Sanster** [comment]
Thank you for supporting my open-source project. This error may have occurred during the installation of dependencies. You can try to fix it with this method: create a new file called `fix.bat` in the `win_start.bat` directory. The content of the file is as follows. After creation, double-click `fix.bat` to execute it:

```bat
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call pip uninstall typing-extensions
@call pip install -U typing-extensions

PAUSE
```
