### ISSUE TITLE
Call the package from own python script

### ISSUE THREAD

**Issue by michaeleggers** [Sanster/IOPaint#534]
**Is your feature request related to a problem? Please describe.**
_I don't find any docs on how to use IOpaint in one's own program._

**Describe the solution you'd like**
_I use Yolo to detect certain objects and create a mask (bounding box). I'd like to be able to directly call IOPaint's
remove functionality from within my own python program._

**Comment by michaeleggers** [comment]
AI sucks

**Comment by Sanster** [comment]
maybe you can try this one: https://github.com/novitalabs/litelama
