### ISSUE TITLE
How to use lama and powerpaint together?

### ISSUE THREAD

**Issue by jryebread** [Sanster/IOPaint#535]
**Model**
lama and powerpaint-v1

**Describe the bug**
When I use both lama and powerpaint v1 inpainting, I don't see an option to use just lama in the UI, only powerpaint version of object removal, which is much slower and worse. How can I use lama when powerpaint is enabled? i think this is a bug.

**System Info**
Software version used
- iopaint: latest
- pytorch: 12.1
- CUDA:12.1

command to run it:
```iopaint start --model=lama --device=cuda --model=Sanster/PowerPaint-V1-stable-diffusion-inpainting --device=cuda --host=0.0.0.0 --enable-realesrgan --realesrgan-model="RealESRGAN_x4plus" --realesrgan-device=cuda  --enable-remove-bg --enable-interactive-seg --interactive-seg-model=vit_l --interactive-seg-device=cuda --disable-nsfw-checker```

**Comment by Sanster** [comment]
Multiple models are not supported. `--model=Sanster/PowerPaint-V1-stable-diffusion-inpainting` is placed after `--model=lama`, so `PowerPaint-V1-stable-diffusion-inpainting` is used when the service starts. You can switch models in the settings on the web page.

**Comment by jryebread** [comment]
@Sanster appreciate your response and creating this cool project!

May i ask which inpainting model you have tried is best for real images? ive been testing them all but found none have worked well for my real image use case (trying to insert new people into existing images)
