### ISSUE TITLE
How to modify the configuration of a model(like using zits) when using command line?

### ISSUE THREAD

**Issue by darewolf-cyber** [Sanster/IOPaint#546]
Dear authors:
   Great project! I've already donated 5 dollars. I know how to modify the configuration of a model, like "crop" or "original" in the GUI window, but I don't know how to do this using a command line, this is especially important when my server can't use GUI. Also, I can use win_config.bat in my win10 computer to modify a setting called "image quality", which is by default 95. But I don't know how to set this by command line.

**Comment by Sanster** [comment]
You can create a 'config.json' file that can refer to this class for configuration https://github.com/Sanster/IOPaint/blob/ef1f7a532421ff40d74bc780662f14ae1ce1c477/iopaint/schema.py#L260

```json
{"hd_strategy": "Resize", "hd_strategy_resize_limit": 300}
```

Use 'config.json' to perform batch processing:

```bash
iopaint run \
--model lama \
--image imgpath or imgdir \
--mask maskpath \
--config config.json \
--output ./tmp
```

Using the 'iopaint run' command, 'image quality' defaults to 100: https://github.com/Sanster/IOPaint/blob/ef1f7a532421ff40d74bc780662f14ae1ce1c477/iopaint/batch_processing.py#L118
