### ISSUE TITLE
[Feature Request] Import existing mask for continued editing

### ISSUE THREAD

**Issue by cpfy** [Sanster/IOPaint#549]
First of all, I'd like to express my sincere gratitude to the author and contributors of IOPaint. This project is truly impressive and has been incredibly helpful for me.

**Is your feature request related to a problem? Please describe.**
Currently, when working on complex inpainting projects, there's no way to save progress mid-way and resume editing later. This can be frustrating when dealing with intricate masks that require multiple editing sessions.

**Describe the solution you'd like**
I would like to request a feature that allows users to import previously created and locally saved masks back into IOPaint. This would enable us to continue refining and modifying existing work without starting from scratch each time.

The ideal workflow would be:
1. Create a mask in IOPaint
2. Save the mask locally
3. Close the project
4. Later, reopen IOPaint and import the saved mask
5. Continue editing and refining the mask

**Additional context**
This feature would be particularly useful for complex projects that require multiple editing sessions or collaborative work. It would also help in situations where users need to take a break from editing but want to preserve their progress.

Thank you for considering this feature request. I believe it would greatly enhance the usability and flexibility of IOPaint for many users.

**Comment by Sanster** [comment]
You can use `-mask-dir` to start the service, and you can select the mask from that directory.

https://www.iopaint.com/file_manager

![image](https://github.com/user-attachments/assets/1970c8d5-c22c-47ca-b209-e63648b3841c)
