### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ironfort9** [Sanster/IOPaint#551]
**Model**
Lama

**Describe the bug**
Error occorred when trying to run via CPU

**Screenshots**
![Errno2](https://github.com/user-attachments/assets/3fb6b83d-f8ca-4853-9215-f6e46a23a3f8)

**System Info**
Software version used

    iopaint: 1.3.3
    pytorch: 2.3.1
    CUDA: 11.8

**Comment by Sanster** [comment]
It may be due to permission issues. Please add the `--model-dir` parameter to specify a path other than the C drive when starting the service.
