### ISSUE TITLE
Issues while installing using pip  install

### ISSUE THREAD

**Issue by github-water** [Sanster/IOPaint#555]
Hi I'm a beginner and I'm facing difficulties to setup this.

I tried to install it using pip, as explained. When I run the code bellow,

pip install lama-cleaner
Following the process occurred the following problems

Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
Can you see what the problem is
Thanks for your help

**Comment by tba-code** [comment]
Hey there, the app was renamed to IOPaint.
You should instead run "pip install IOPaint".
