### ISSUE TITLE
我的无法使用英伟达的GPU，直接使用RealESRGAN时是可以使用GPU的，但是在iopaint中却无法调用GPU。

### ISSUE THREAD

**Issue by xiaowangaixuexijishu** [Sanster/IOPaint#557]
![屏幕截图 2024-08-12 172016](https://github.com/user-attachments/assets/d802bc28-8e58-45a6-8a20-3afa17d2f2f6)

**Comment by Sanster** [comment]
是不是使用 RealEsrGAN 的 python 环境和 iopaint 的 python 不一样？这个错误提示很明显了，安装的 torch 版本不支持 gpu

**Comment by xiaowangaixuexijishu** [comment]
我的torch 版本支持 gpu的，而且我单独使用 RealEsrGAN时torch也是调用了GPU的
![image](https://github.com/user-attachments/assets/9c20a4a2-373b-4b18-a684-7579d410bb46)

**Comment by xiaowangaixuexijishu** [comment]
好我已经解决了，感谢你的解答。
