### ISSUE TITLE
[BUG] - Sam v2 is not working on the latest version: IOPaint-1.4.2

### ISSUE THREAD

**Issue by AlonDan** [Sanster/IOPaint#563]
**Describe the bug**
Launching the latest version IOPaint-1.4.2 works only without the new Sam2.

I've added the following to the .bat file:
`--enable-interactive-seg --interactive-seg-model=sam2_base  --interactive-seg-device=cuda`

And I get the error that says:
```
┌─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Invalid value for '--interactive-seg-model': 'sam2_base' is not one of 'vit_b', 'vit_l', 'vit_h', 'sam_hq_vit_b',   │
│ 'sam_hq_vit_l', 'sam_hq_vit_h', 'mobile_sam'.                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Press any key to continue . . .
```

✅ Just to be clear it works fine with the old **Sam v1** no issues at all.

**Screenshots**
![cmd_2024-08-27_14-26-50](https://github.com/user-attachments/assets/06a51772-7c68-4813-8e66-de8bbe83b554)

---

Do I need to download **Sam2** models manually?
If so where from and in what directory in IOPaint should I put them?

Thanks ahead 🙏

**Comment by Sanster** [comment]
- The sam2 model does not need to be manually downloaded, it will automatically download at startup.
- Can you confirm the version of iopaint? The version number will be printed when the service starts. Based on the error message, it seems you are using an older version.
<img width="413" alt="image" src="https://github.com/user-attachments/assets/d927dd8a-ce8c-4cf6-8ba4-973bb12194af">

**Comment by AlonDan** [comment]
Thanks for the detailed reply,
This is strange because I definatly downloaded and used the latest ZIP (source) from the website and even the file name is: `IOPaint-iopaint-1.4.2`

This is the .bat file I'm using to launch it:  
(ignore the part with old SAM v1 because I can't run Sam2 at the moment)
```
@echo off

CD IOPaint-iopaint-1.4.2

start http://127.0.0.1:8080

iopaint start --device=cuda --port=8080 --model=uberRealisticPornMerge_urpmv13Inpainting.safetensors --output-dir=C:\IOPaint --enable-remove-bg --remove-bg-model=briaai/RMBG-1.4 --enable-interactive-seg --interactive-seg-model=sam_hq_vit_h --interactive-seg-device=cuda --disable-nsfw-checker


pause
```

Am I missing something?
