### ISSUE TITLE
[BUG] ImportError after clean install and first run

### ISSUE THREAD

**Issue by mploigt** [Sanster/IOPaint#580]
I am on an M1 Mac and I can't run iopaint.

- I ran `pip install iopaint` successfully
- When I run `iopaint start --model=lama --device=cpu --port=8080` I get this error:
  `ImportError: dlopen(/opt/anaconda3/lib/python3.12/site-packages/PIL/_imaging.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_opj_encoder_set_extra_options'`

Complete install and error log: [install_error_log.txt](https://github.com/user-attachments/files/17377466/install_error_log.txt)

**Comment by Sanster** [comment]
It should be related to the Python version; please try using 3.10.
