### ISSUE TITLE
[BUG]ImportError: cannot import name 'cached_download' from 'huggingface_hub' (d:\anaconda3\lib\site-packages\huggingface_hub\__init__.py)

### ISSUE THREAD

**Issue by b67294** [Sanster/IOPaint#581]
**Model**
lama-cleaner

**Describe the bug**
when i double click the "win_start.bat"after win_config.bat.it shows “ImportError: cannot import name 'cached_download' from 'huggingface_hub' (d:\anaconda3\lib\site-packages\huggingface_hub\__init__.py)”

**Screenshots**
![JC0$G~OAM %FZ3~0{ _BQUV](https://github.com/user-attachments/assets/0d2911d1-fada-4b53-a78e-6fd617d80586)

**System Info**
Software version used
- iopaint: 
- pytorch: 
- CUDA:

**Comment by Sanster** [comment]
This is due to API compatibility issues caused by the upgrade of huggingface_hub, which has been fixed in IOPaint 1.4.4.
