### ISSUE TITLE
Where is the update one click

### ISSUE THREAD

**Issue by Tobe2d** [Sanster/IOPaint#590]
I cant see the new update avalibale on the one click installer website

IOPaint is outdated since v1

![image](https://github.com/user-attachments/assets/83238c27-bceb-48c3-9006-54014cf82388)

**Comment by Moltresrider** [comment]
Appears to be a scam. The GitHub claims it is free but asks you to pay for it

**Comment by Tobe2d** [comment]
No no its not scame, the free one you compile yourself but the 1-click install is for $5 to support the dev.

**Comment by Sanster** [comment]
> I cant see the new update avalibale on the one click installer website
> 
> IOPaint is outdated since v1
> 
> ![image](https://private-user-images.githubusercontent.com/4099839/382462350-83238c27-bceb-48c3-9006-54014cf82388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzAwMzQsIm5iZiI6MTczMDc2OTczNCwicGF0aCI6Ii80MDk5ODM5LzM4MjQ2MjM1MC04MzIzOGMyNy1iY2ViLTQ4YzMtOTAwNi01NDAxNGNmODIzODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDEyMjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNmNGJiYTNjMjEwMmEyMWUzMzI5MjdmNzcyOWI3YzA5NDFlNGY2NjM4MzZhODEzYjFhNmJmZTBkNjNmNzA1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2ulfxT3ejdYNURDCLw77UFu7Y89THPzSNUfQ52NV9Us)

<img width="227" alt="image" src="https://github.com/user-attachments/assets/d4bfa4ff-000d-4dad-9494-552aa287f004">

I have uploaded a new compressed file, which is basically the same, just with the original script split up.

- win_setup.bat: Script used for the first installation of dependencies
- win_config.bat: Modify and save configuration
- win_start.bat: Script used to start the service
- win_update.bat: Script used to update iopaint.

**Comment by Tobe2d** [comment]
@Sanster  Thank you so much it works now!
