### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by djekra** [Sanster/IOPaint#592]
**Model**
lama

**Describe the bug**
The web app shows only a empty page. The title is "IOPaint" but the body is empty. HTML Source below.

INFO:     127.0.0.1:51305 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51305 - "GET /assets/index-ydVO5PAq.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51306 - "GET /assets/index-0foJStMW.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51305 - "GET /favicon.ico HTTP/1.1" 404 Not Found

I fixed the 404 but this was not the problem.

**System Info**
Software version used
- iopaint: 1.5.0
- pytorch: 
- CUDA:
- Windows 10

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IOPaint</title>
    <script type="module" crossorigin src="[/assets/index-ydVO5PAq.js](http://localhost:8090/assets/index-ydVO5PAq.js)"></script>
    <link rel="stylesheet" crossorigin href="[/assets/index-0foJStMW.css](http://localhost:8090/assets/index-0foJStMW.css)">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

**Comment by Sanster** [comment]
Can you try the methods in this issue to see if they work?  https://github.com/Sanster/IOPaint/issues/460
