### ISSUE TITLE
Can't start the UI using the paid/donated scripts

### ISSUE THREAD

**Issue by mesopa** [Sanster/IOPaint#593]
**Model**
IOPaint-v1.1

**Describe the bug**
After running both `win_setup.bat` and `win_config.bat`, when running the script `win_start.bat`, it doesn't start and exists with the error `ModuleNotFoundError: No module named 'iopath'`.

No matter if I put on the root of C drive or any other drive. Also modifying the file `site.py`, do not solve the problem.

**Screenshots**
![image](https://github.com/user-attachments/assets/2f209a6c-9294-4055-8f4c-bff844d743ae)

**System Info**
Software version used
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.6
- torch: 2.1.2+cu118
- torchvision: 0.16.2+cu118
- Pillow: 9.5.0
- diffusers: 0.27.2
- transformers: 4.46.1
- opencv-python: 4.10.0.84
- accelerate: 1.1.0
- iopaint: 1.5.0
- rembg: 2.0.59

**Comment by Doktorhak** [comment]
I have the same problem
