### ISSUE TITLE
[BUG] Lama Cleaner is broken

### ISSUE THREAD

**Issue by Moltresrider** [Sanster/IOPaint#594]
**Model**
None. website completely does not work

**Describe the bug**
Going to your official Lama Cleaner Hugging Face page, the website no longer works. It worked a couple months ago but it does not work anymore. 

I always get the following error message every time I load it

===== Application Startup at 2024-11-03 20:14:00 =====

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]
0it [00:00, ?it/s]
2024-11-03 21:15:07.106 | INFO     | lama_cleaner.server:build_plugins:481 - Initialize InteractiveSeg plugin
Downloading: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth" to /home/user/.cache/torch/hub/checkpoints/sam_vit_b_01ec64.pth

  0%|          | 0.00/358M [00:00<?, ?B/s]
  3%|▎         | 11.2M/358M [00:00<00:03, 115MB/s]
 10%|▉         | 34.7M/358M [00:00<00:01, 192MB/s]
 15%|█▍        | 53.1M/358M [00:00<00:01, 188MB/s]
 20%|█▉        | 71.1M/358M [00:00<00:01, 188MB/s]
 25%|██▍       | 89.0M/358M [00:00<00:01, 178MB/s]
 31%|███       | 110M/358M [00:00<00:01, 191MB/s] 
 36%|███▌      | 128M/358M [00:00<00:01, 192MB/s]
 41%|████      | 147M/358M [00:00<00:01, 190MB/s]
 48%|████▊     | 173M/358M [00:00<00:00, 215MB/s]
 55%|█████▍    | 196M/358M [00:01<00:00, 223MB/s]
 61%|██████    | 219M/358M [00:01<00:00, 227MB/s]
 67%|██████▋   | 240M/358M [00:01<00:00, 214MB/s]
 75%|███████▌  | 269M/358M [00:01<00:00, 237MB/s]
 82%|████████▏ | 293M/358M [00:01<00:00, 244MB/s]
 89%|████████▉ | 320M/358M [00:01<00:00, 254MB/s]
 97%|█████████▋| 345M/358M [00:01<00:00, 257MB/s]
100%|██████████| 358M/358M [00:01<00:00, 221MB/s]

Refreshing the page does literally nothing and there is no option to do anything else.
**Screenshots**

![Screenshot 2024-11-03 at 22-43-53 Lama Cleaner Lama - a Hugging Face Space by Sanster](https://github.com/user-attachments/assets/42b12b20-f362-44bd-96f0-25a15012c788)

**System Info**
Software version used
Lama Cleaner Website

**Comment by Sanster** [comment]
fixed
