### ISSUE TITLE
[Feature Request]After using the GFPGAN plug-in to repair a photo, I want to change the color of the face and clothes. Is it supported?

### ISSUE THREAD

**Issue by 0x22E09-8** [Sanster/IOPaint#596]
**Is your feature request related to a problem? Please describe.**
After using the GFPGAN plug-in to repair a photo, I want to change the color of the face and clothes. Is it supported?

**Describe the solution you'd like**
You can change the customizable colors of people's faces and clothes to make them look more suitable for the scene

**Additional context**

**Comment by Sanster** [comment]
你可以使用 diffusion 模型来完成这个修改，例如 [brushnet](https://www.iopaint.com/models/diffusion/brushnet) 或者  [PowerPaintV2](https://www.iopaint.com/models/diffusion/powerpaint_v2)
