### ISSUE TITLE
[BUG] so many loading

### ISSUE THREAD

**Issue by xu2k** [Sanster/IOPaint#600]
"host": "127.0.0.1",
    "port": 8080,
    "inbrowser": true,
    "model": "Sanster/PowerPaint-V1-stable-diffusion-inpainting",
    "no_half": false,
    "low_mem": false,
    "cpu_offload": false,
    "disable_nsfw_checker": false,
    "local_files_only": true,
    "cpu_textencoder": false,
    "device": "cpu",
    "input": null,
    "mask_dir": null,
    "output_dir": null,
    "quality": 95,
    "enable_interactive_seg": false,
    "interactive_seg_model": "sam2_1_tiny",
    "interactive_seg_device": "cpu",
    "enable_remove_bg": false,
    "remove_bg_model": "briaai/RMBG-1.4",
    "enable_anime_seg": false,
    "enable_realesrgan": false,
    "realesrgan_device": "cpu",
    "realesrgan_model": "realesr-general-x4v3",
    "enable_gfpgan": false,
    "gfpgan_device": "cpu",
    "enable_restoreformer": false,
    "restoreformer_device": "cpu"

I purchased IOPaint and started inpainting, but it's stuck at 2%.

What could be the issue?

**Comment by Sanster** [comment]
The first time you use the model, it will download the model, and the download speed is related to the network.

**Comment by Sanster** [comment]
Hi, I'm temporarily closing this issue for now. If Iopaint is not helpful to you, feel free to email me anytime to request a refund.
